FROM fj0rd/io

RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y \
  ; mkdir -p /usr/share/man/man1 \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      openjdk-11-jdk \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

RUN set -eux \
  ; for x in java metals \
  ; do nvim -u /etc/skel/.config/nvim/init.vim --headless +"CocInstall -sync coc-$x" +qa; done \
  \
  ; mkdir -p /opt/language-server/java \
  ; jdtls_latest=$(curl https://download.eclipse.org/jdtls/snapshots/latest.txt) \
  ; curl https://download.eclipse.org/jdtls/snapshots/${jdtls_latest} \
    | tar --no-same-owner -zxf - -C /opt/language-server/java \
  ; echo "let g:coc_user_config['java.jdt.ls.home'] = '/opt/language-server/java'" >> /etc/skel/.config/nvim/config.coc/lsp.vim \
  \
  ; npm cache clean -f

ENV SCALA_HOME=/opt/scala
ENV PATH=${SCALA_HOME}/bin:$PATH

RUN set -eux \
  ; mkdir -p /usr/share/man/man1 \
  ; mkdir -p ${SCALA_HOME} \
  ; curl -sSL $(curl -sSL https://scala-lang.org/download/|pup '[id="#link-main-unixsys"] attr{href}') \
      | tar xzf - -C ${SCALA_HOME} --strip-components=1

ARG github_header="Accept: application/vnd.github.v3+json"
ARG github_api=https://api.github.com/repos
ARG mill_repo=lihaoyi/mill

RUN set -eux \
  ; mill_version=$(curl -sSL -H "'$github_header'" $github_api/${mill_repo}/releases | jq -r '.[0].tag_name') \
  ; curl -L https://github.com/lihaoyi/mill/releases/download/${mill_version}/${mill_version} > /usr/local/bin/mill \
  ; chmod +x /usr/local/bin/mill

ARG metals_repo=scalameta/metals

RUN set -eux \
  ; metals_version=$(curl -sSL -H "'$github_header'" $github_api/${metals_repo}/releases | jq -r '.[0].tag_name'|cut -c 2-) \
  ; java -Dfile.encoding=UTF-8 -jar \
    /etc/skel/.config/nvim/coc-data/extensions/node_modules/coc-metals/coursier \
    fetch -p --ttl Inf org.scalameta:metals_2.12:${metals_version} \
    -r bintray:scalacenter/releases \
    -r sonatype:public \
    -r sonatype:snapshots -p

