FROM nnurphy/ub:latest

RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      build-essential openjdk-8-jdk \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# ENV JAVA_HOME=/usr
RUN set -eux \
  ; for x in java metals \
  ; do nvim -u /etc/skel/.config/nvim/init.vim --headless +"CocInstall -sync coc-$x" +qa; done \
  \
  ; mkdir -p /opt/language-server/java \
  ; jdtls_latest=$(curl https://download.eclipse.org/jdtls/snapshots/latest.txt) \
  ; curl https://download.eclipse.org/jdtls/snapshots/${jdtls_latest} \
    | tar --no-same-owner -zxf - -C /opt/language-server/java \
  ; echo "let g:coc_user_config['java.jdt.ls.home'] = '/opt/language-server/java'" >> /etc/skel/.config/nvim/config.coc/lsp.vim \
  \
  ; npm cache clean -f

ENV SCALA_HOME=/opt/scala
ENV PATH=${SCALA_HOME}/bin:$PATH

RUN set -eux \
  ; mkdir -p /usr/share/man/man1 \
  ; mkdir -p ${SCALA_HOME} \
  ; wget -qO- $(curl -sSL https://scala-lang.org/download/|pup '[id="#link-main-unixsys"] attr{href}') \
      | tar xzf - -C ${SCALA_HOME} --strip-components=1

ARG github_header="Accept: application/vnd.github.v3+json"
ARG github_api=https://api.github.com/repos
ARG mill_repo=lihaoyi/mill

RUN set -eux \
  ; mill_version=$(curl -sSL -H "'$github_header'" $github_api/${mill_repo}/releases | jq -r '.[0].tag_name') \
  ; curl -L https://github.com/lihaoyi/mill/releases/download/${mill_version}/${mill_version} > /usr/local/bin/mill \
  ; chmod +x /usr/local/bin/mill

ARG metals_repo=scalameta/metals

RUN set -eux \
  ; metals_version=$(curl -sSL -H "'$github_header'" $github_api/${metals_repo}/releases | jq -r '.[0].tag_name') \
  ; echo $metals_version \
  ; curl -L -o /usr/local/bin/coursier https://git.io/coursier-cli \
  ; chmod +x /usr/local/bin/coursier \
  ; coursier bootstrap \
      --java-opt -Xss4m \
      --java-opt -Xms100m \
      --java-opt -Dmetals.client=vim-lsc \
      org.scalameta:metals_2.13:0.9.10 \
      -r bintray:scalacenter/releases \
      -r sonatype:snapshots \
      -o /usr/local/bin/metals-vim -f

