FROM nnurphy/ub:latest

RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      build-essential default-jdk \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr
RUN set -eux \
  ; for x in java metals \
  ; do nvim -u /etc/skel/.config/nvim/init.vim --headless +"CocInstall -sync coc-$x" +qa; done \
  \
  ; mkdir -p /opt/language-server/java \
  ; curl https://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.68.0-202012242230.tar.gz \
    | tar --no-same-owner -zxf - -C /opt/language-server/java \
  ; echo "let g:coc_user_config['java.jdt.ls.home'] = '/opt/language-server/java'" >> /etc/skel/.config/nvim/config.coc/lsp.vim \
  \
  #; npm config set registry https://registry.npm.taobao.org \
  ; npm cache clean -f

ENV SCALA_HOME=/opt/scala
ENV PATH=${SCALA_HOME}/bin:$PATH

RUN set -eux \
  ; mkdir -p /usr/share/man/man1 \
  ; mkdir -p ${SCALA_HOME} \
  ; wget -qO- $(curl -sSL https://scala-lang.org/download/|pup '[id="#link-main-unixsys"] attr{href}') \
      | tar xzf - -C ${SCALA_HOME} --strip-components=1

ARG github_header="Accept: application/vnd.github.v3+json"
ARG github_api=https://api.github.com/repos
ARG mill_repo=lihaoyi/mill

RUN set -eux \
  ; mill_version=$(curl -sSL -H "'$github_header'" $github_api/${mill_repo}/releases | jq -r '.[0].tag_name') \
  ; curl -L https://github.com/lihaoyi/mill/releases/download/${mill_version}/${mill_version} > /usr/local/bin/mill \
  ; chmod +x /usr/local/bin/mill

